name: Build README

on:
  workflow_dispatch: {}
  schedule:
    # Run a bit after the sync job
    - cron: "50 13 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate README table
        run: |
          node scripts/build_readme.mjs

      - name: Commit README if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          if ! git diff --cached --quiet; then
            git commit -m "chore: update README problem table"
            git push
          fi
